spring.application.name=backend-gimnasio
server.port=8080
# Configuraci\u00F3n de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/gym?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Liquibase
spring.liquibase.change-log=classpath:liquibase/master_changelog.xml
spring.liquibase.enabled=false

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.stat=OFF



# jwt audience (client_id) and issuer (to validate in JWT)
jwt.issuer=https://securetoken.google.com/gimnasio-iro
jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
jwt.audience=gimnasio-iron
